[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000

# Remappings for v4-core
remappings = [
    "v4-core/=lib/v4-core/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "solmate/=lib/v4-core/lib/solmate/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
